### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by smacker** [smacker/go-tree-sitter#10]
`go build` runs `go get` which is fails as there is no c code when this project is used as a dependency.

**Comment by smacker** [comment]
Originally I used git submodules but resorted to a makefile instead due to #6
Go modules don't support git submodules so it is not an option anymore.

Looks like the only option now is to vendor the source code of tree-sitter and grammars.

**Comment by RichardFevrier** [comment]
Hi @smacker nice optimisation. Would it be possible to put the original source files into a separate folder named like a submodule e.g `tree-sitter @ 889dcef` just for clarity reason?
