### ISSUE TITLE
Adding predicates clause(s) *increases* the number of results

### ISSUE THREAD

**Issue by broofa** [smacker/go-tree-sitter#103]
My apologies if this isn't the right place for this.  I'm trying to wrap my head around how the `tree-sitter` project works, and how libs like `go-tree-sitter` are / aren't expected to add predicate support.
 
Specifically: Is it expected that adding predicates to a query may *increase* the number of returned `Match` results?

In https://github.com/codepen/go-tree-sitter/pull/10 I have a test that runs a few variations of a simple `comment` query against the same 3-comment input document.  I would expect to get 3 results each time since I'm specifically **NOT** calling `FilterPredicates()`. What I see, however, is the following:

|  query | `Match` count |
|---|---|
| `(expression (comment) @foo)` | 3 |
| `(expression (comment) @foo (#match? @foo "^// the") )` | 3 |
| `(expression (comment) @foo) (#match? @foo "^// the")` | 8 |
| `(expression (comment) @foo) (#match? @foo "^// the") (#match? @foo "water$")` | 13 |

## Specific questions
- Is this behavior expected?
- Is it something `tree-sitter` does?
- ... or is this some how caused by the golang bindings that `go-tree-sitter` provides

I'm asking because the predicate support added in #83 seems... confusing.  And also incomplete. (See also #92 and #101).  I'm contemplating putting up a PR that reworks this code somewhat, but I'd like to get a sense from you (@smacker) if that's something you'd be open to, and get your thoughts on how you'd like to see that (re)implemented.

**Comment by smacker** [comment]
Hello @broofa 

> Is it expected that adding predicates to a query may increase the number of returned Match results?

It is not expected as long as the query is written correctly.

I checked your tests and I see on current master the first 2 tests pass as expected and the 2 last tests fail as expected. Please see documentation for predicates here: https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries .

When I fix the query
```go
// before
assert.Equal(
	t,
	3,
	evalQuery(`
		(expression (comment) @foo)
		(#match? @foo "^// the")
	`),
)
// after
assert.Equal(
	t,
	3,
	evalQuery(`(
		(expression (comment) @foo)
		(#match? @foo "^// the")
	)`),
)
```

The test correctly pass.

The test
```go
assert.Equal(
  t,
  3,
  evalQuery(`(
    (expression (comment) @foo)
      (#match? @foo "^// the")
      (#match? @foo "water$")
  )`),
)
```
produces error "Failed to parse query wrong number of arguments to `#match?` predicate. Expected 2, got 6" which does look like a bug in `go-tree-sitter` binding.

> I'm asking because the predicate support added in https://github.com/smacker/go-tree-sitter/pull/83 seems... confusing. And also incomplete. I'm contemplating putting up a PR that reworks this code somewhat

The predicate support is indeed a new feature implemented recently and can be improved. Please feel free to contribute!

> get your thoughts on how you'd like to see that (re)implemented

[Rust](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_rust/README.md) and [JS](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web) bindings are the best reference. Keeping the code as close as possible to them would simplify porting of any new features related to predicates in the future.

**Comment by smacker** [comment]
PR with the fix for multiple predicates has been merged. Please try again and feel free to re-open the issue if the problem was not fixed.
