### ISSUE TITLE
Grammar update script not working

### ISSUE THREAD

**Issue by sadfun** [smacker/go-tree-sitter#132]
Any attempt to update a grammar without modifying `grammars.json` manually results in 404 error:

```bash
downloading language=python reference=v0.20.4
incorrect response status code reference=v0.20.4 url=https://raw.githubusercontent.com/tree-sitter/tree-sitter-python/5083d4e4a29d8672b413f19dcdcf0a016eb975d6/src/tree_sitter/parser.h language=python 0=statusCode 1=404
```

The issue applies to all grammars. It looks like `git ls-remote` returns some other hashes, not pullable from https://raw.githubusercontent.com.

**Comment by smacker** [comment]
This should be fixed by https://github.com/smacker/go-tree-sitter/pull/133
