### ISSUE TITLE
Missing typescript module

### ISSUE THREAD

**Issue by corey-cole** [smacker/go-tree-sitter#153]
Tweaking the README example from javascript to typescript results in an import error

```go
package main

import (
	sitter "github.com/smacker/go-tree-sitter"
	"github.com/smacker/go-tree-sitter/typescript"
)

func main() {
	ts := sitter.New()
	ts.SetLanguage(typescript.GetLanguage())
}
```

Installing deps for my project:
```
go get .
go: github.com/corey-cole/sitter-test imports
	github.com/smacker/go-tree-sitter/typescript: cannot find module providing package github.com/smacker/go-tree-sitter/typescript
```

Explicit install:
```
go get github.com/smacker/go-tree-sitter/typescript
go: module github.com/smacker/go-tree-sitter@upgrade found (v0.0.0-20240320021847-a4b649a78290), but does not contain package github.com/smacker/go-tree-sitter/typescript
```

Tried with a few other languages (javascript and csharp) without the same issue.

**Comment by alexaandru** [comment]
The correct import path is "github.com/smacker/go-tree-sitter/typescript/typescript". The typescript repo implements two parsers: typescript and tsx, and the folder you imported holds both, so you need to pick the one you actually want.
