### ISSUE TITLE
Python 2/3

### ISSUE THREAD

**Issue by kuba--** [smacker/go-tree-sitter#21]
Would you consider replace current python (which afaik is a parser for python2) by python3 or at least add both?

**Comment by smacker** [comment]
Hi Kuba!

Python parser uses grammar of [tree-sitter-python v0.15.0](https://github.com/tree-sitter/tree-sitter-python/tree/v0.15.0). I didn't test it but according to the [examples](https://github.com/tree-sitter/tree-sitter-python/tree/v0.15.0/examples) it supports both python2 & python3.

Please let me know what doesn't work for you and which grammar do you want to use instead.

**Comment by kuba--** [comment]
It's very related to @dennwc PR (https://github.com/smacker/go-tree-sitter/pull/23), but you can also take a look into diffs between my fork (python parser): 
https://github.com/smacker/go-tree-sitter/compare/master...kuba--:master

From practical point of view the most important for us is to be able run queries. For instance following queries (to extract python imports):
```
((import_statement name: (dotted_name (identifier)) @name))
((import_statement name: (aliased_import name: (dotted_name (identifier)) @name)))
((import_from_statement module_name: (dotted_name (identifier)) @name))
((import_from_statement module_name: (relative_import (import_prefix)) @name))
```
panic with the python parser in your repo.

**Comment by smacker** [comment]
the latest released grammar for python doesn't support field names.

The query doesn't panic but returns
```
field error (offset: 19)
```
which informs you that the query is incorrect.
It is important to write queries for correct versions of grammars.

Anyway your query problem isn't related to support for python3.
Should we just close the issue?

**Comment by kuba--** [comment]
Right, it returns an error.
Anyway, my point was to suggest replace python parser by the new one which let us use named fields.
This issue was just an open question. We can totally close it, because it's up to you if you want to update the python parser (which supports named queries).

**Comment by smacker** [comment]
We will definitely update it as soon as the new version is released in upstream. Thanks.
