### ISSUE TITLE
suppress compilation warning (C#)

### ISSUE THREAD

**Issue by kuba--** [smacker/go-tree-sitter#25]
Please add following line to the file `csharp/parser.c` to suppress compilation warning (parser.c:527:32: warning: trigraph ignored [-Wtrigraphs]):

```
#pragma GCC diagnostic ignored "-Wtrigraphs"
```

**Comment by smacker** [comment]
Hi @kuba-- !
The issue was solved here: https://github.com/smacker/go-tree-sitter/commit/1a56f9a8707d9c7f09f49195e019a562a27ae2d7
