### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by p-e-w** [smacker/go-tree-sitter#29]
While testing in Micro, I noticed that parsing and getting the root node of a tree leaks a large amount of memory. Minimal example to reproduce:

```go
package main

import (
	"fmt"
	"sync"
	sitter "github.com/smacker/go-tree-sitter"
	"github.com/smacker/go-tree-sitter/javascript"
)

func main() {
	runTest()
	fmt.Println("done.")

	// Wait forever
	var lock sync.Mutex
	lock.Lock()
	lock.Lock()
}

func runTest() {
	parser := sitter.NewParser()
	parser.SetLanguage(javascript.GetLanguage())
	sourceCode := []byte("let a = 1")

	for i := 0; i < 500000; i++ {
		// Leaks 115 Megabytes
		tree := parser.Parse(sourceCode)
		// Leaks 525 Megabytes
		tree.RootNode()
	}
}
```

After printing `done`, `runTest` has returned and all variables related to tree-sitter are out of scope and their objects will be garbage collected. However, a whopping **640 Megabytes** of memory is never freed, more than 1 kB per iteration despite the source code being only 9 bytes.

When the source code is larger, the amount of memory leaked per parse can exceed 1 MB. In Micro, I have seen more than 100 MB leak during one minute of normal use.

**Comment by smacker** [comment]
thank you for the report. I have fixed it here: https://github.com/smacker/go-tree-sitter/commit/8c6c6df58bf4bbf0d441d7cb4a77d2a2b721eda8
