### ISSUE TITLE
json output format

### ISSUE THREAD

**Issue by vaibhavnshah** [smacker/go-tree-sitter#37]
Is there a way to get or easily process the tree output as json?

**Comment by patrickdevivo** [comment]
was wondering about this as well, I noticed in the [nodejs bindings](https://github.com/tree-sitter/node-tree-sitter) there's an example of how to output the json representation of a parsed tree (or at least a node in it). Is it possible to do the same using this library? Thanks!

**Comment by patrickdevivo** [comment]
> was wondering about this as well, I noticed in the [nodejs bindings](https://github.com/tree-sitter/node-tree-sitter) there's an example of how to output the json representation of a parsed tree (or at least a node in it). Is it possible to do the same using this library? Thanks!

Actually, looking a bit closer it looks like that example in the nodejs README is just the `console.log` output of a JS object representing a node, which looks like JSON but isn't.

**Comment by smacker** [comment]
Hi @vaibhavnshah !

The library doesn't provide any built-in method to output a tree as json.
Though it should be fairly simple to implement in your app code using [Iterator](https://pkg.go.dev/github.com/smacker/go-tree-sitter?utm_source=godoc#NewNamedIterator).
