### ISSUE TITLE
Update required version of github.com/stretchr/testify.

### ISSUE THREAD

**Issue by m-kru** [smacker/go-tree-sitter#73]
The currently used version pulls in `gopkg.in/yaml.v2 v2.2.2` which cases github vulnerabilities alert. Current version of testify pulls in `gopkg.in/yaml.v3 v3.0.1`.

**Comment by smacker** [comment]
Updated here: https://github.com/smacker/go-tree-sitter/commit/1191a8204295ea48d1d5fb2e6fd51474b13f94de
