### ISSUE TITLE
Handle predicates

### ISSUE THREAD

**Issue by grouville** [smacker/go-tree-sitter#77]
When playing with the queries of `go-tree-sitter`, I realized (not 100% sure, but 95%) that it doesn't handle predicates such as:

```
(
  (identifier) @constant
  (#match? @constant "^[A-Z][A-Z_]+")
)
```
It gets matched, but not perfectly: there are duplicates, and the constraint of the match doesn't get applied.

According to the [docs](https://tree-sitter.github.io/tree-sitter/using-parsers#predicates):
> Note - Predicates are not handled directly by the Tree-sitter C library. They are just exposed in a structured form so that higher-level code can perform the filtering. However, higher-level bindings to Tree-sitter like [the Rust crate](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_rust) or the [WebAssembly binding](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web) implement a few common predicates like #eq? and #match?.

As this binding is relying on the C libraries (from what I understand), there's a great chance that this is not implemented at all.
I don't know where to start, if it's hard or not. But this would be an awesome addition, and would love to help on that 😇 

PS: tested on the `cue` binding

**Comment by smacker** [comment]
Hi @grouville !

You are correct. The predicates are not implemented in this library. Currently, the binding just exposes Tree-sitter C library in Go without (almost) any logic on top.

I agree it would be nice to implement predicates to be compatible with Rust and JS bindings.

If you are willing to contribute the starting point would be [query](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.js#L666) method in JS binding (or you can find the same in the rust one if you are more comfortable with rust). The logic there is somewhat straightforward and probably can be ported almost as-is to Go.

**Comment by smacker** [comment]
This was implemented, thanks to @PKuebler.
