### ISSUE TITLE
Add go.mod grammar

### ISSUE THREAD

**Issue by andrerfcsantos** [smacker/go-tree-sitter#78]
I think a pretty nice addition to the list of grammars supported by default would be [tree-sitter-go-mod](https://github.com/camdencheek/tree-sitter-go-mod) to parse the contents of `go.mod` files.

My use case is I'm using tree sitter to parse and analyze some Go code, and as part of that, some things I want to implement require me to read `go.mod` .Would be nice to use tree sitter for this.

**Comment by smacker** [comment]
Hi @andrerfcsantos ! You can add any grammar to you project with a simple binding file like here: https://github.com/smacker/go-tree-sitter/pull/58
