### ISSUE TITLE
Go printing "verbs" highlight group.

### ISSUE THREAD

**Issue by ameddin73** [smacker/go-tree-sitter#84]
Currently, the only substring that gets a group is `escape_sequence`. Go has a collection of "verbs" you can see in the [fmt package](https://pkg.go.dev/fmt) that should be highlighted as well in their own like `print_verb`.

It's very difficult to disambiguate placeholders in a string without syntax highlighting.
Here the escape rune is easy to find, but not the print verb.
![image](https://user-images.githubusercontent.com/6893820/194119327-e5258309-1deb-4f0f-a5db-2243b18acdc5.png)

**Comment by smacker** [comment]
hi @ameddin73 ! You probably submitted the issue to the wrong repository. This project doesn't provide any highlighting capabilities. And if you are looking for golang grammar for tree-sitter you need this repository: https://github.com/tree-sitter/tree-sitter-go

**Comment by ameddin73** [comment]
Oops
