### ISSUE TITLE
Question: cannot parse without language

### ISSUE THREAD

**Issue by phileagleson** [smacker/go-tree-sitter#85]
I apologize if this isn't the right place to ask this question. If there is somewhere more appropriate this should go please let me know.

I created a new tree-sitter-poweron parser for a language used by my company. It works as expected in neovim. 
When I add the required files to this repo and attempt to test, I'm getting a "cannot parse without language" error. I hoping someone can point me in the right direction for this. If I remove the "externals" from the tree-sitter grammar and add it without the scanner.c, the test passes but of course I need the external scanner to properly match a few tokens.

Updates are here:
https://github.com/phileagleson/go-tree-sitter/tree/tree-sitter-poweron

and the tree-sitter-poweron repo is here:
https://github.com/phileagleson/tree-sitter-poweron

Please let me know if there is any additional information that would be helpful

**Comment by eprst** [comment]
You generated using tree-sitter 20.7, which resulted in `LANGUAGE_VERSION=14` (see your `parser.c`), while this binding is based on `20.0` which understands up to version 13, see `TREE_SITTER_LANGUAGE_VERSION 13` in `api.h`.

I just created https://github.com/smacker/go-tree-sitter/issues/86 asking for a bump
