### ISSUE TITLE
parse error when return type is generic

### ISSUE THREAD

**Issue by williamfzc** [smacker/go-tree-sitter#87]
```go
func Abcd[T DataType](result *BaseFileResult[T]) []T {
	return nil
}
```

![image](https://user-images.githubusercontent.com/13421694/197718908-148431d7-9b35-45b4-9d0c-7e8fc755bc8f.png)

It reports some errors. Looks like it caused by return value `[]T`

using latest version:
github.com/smacker/go-tree-sitter v0.0.0-20221023091341-2009a4db91e4

**Comment by smacker** [comment]
Hi @williamfzc . I have updated the [grammar](https://github.com/tree-sitter/tree-sitter-go) in this repo, it should fix the error.

**Comment by williamfzc** [comment]
it works
thanks for your help!
